# File is used by springboot
server:
     contextPath: /
     port: 9119

# comment bellowing out to enable jwt security
security:
    ignored=/**


spring:
    datasource:
        url: jdbc:mysql://beta.wcare.cn:3306/screw?allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
        driverClassName: com.mysql.jdbc.Driver
        username: screw
        password: Screw@123

    data:
        mongodb:
            uri: mongodb://screw:Screw[123@beta.wcare.cn:38027/screw


    resources:
        static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/webui/

#Temporary disable security to enable it remove this
#security.ignored=/**

springfox:
    documentation:
        swagger.v2.path: /controller-docs

#mybatis:
##  type-aliases-package: com.example.junior.Entity  //这里是实体类所在的包
#  mapper-locations: classpath:/mapper/*.xml  //这里是放sql语句的映射文件

